// Metadata for all 26 games and their specific engine associations
const gamesData = [
  { id: 1, title: 'Royal Teen Patti', tag: 'Card Game', icon: '🃏', engine: 'teenpatti' },
  { id: 2, title: 'Royal Ludo', tag: 'Board Game', icon: '🎲', engine: 'ludo' },
  { id: 3, title: 'Dragon Fortune', tag: 'Slot', icon: '🐉', engine: 'slot', symbols: ['🐉','🔥','💎','👑','🪙'] },
  { id: 4, title: 'Golden Goddess', tag: 'Slot', icon: '👸', engine: 'slot', symbols: ['👸','✨','💎','👑','🪞'] },
  { id: 5, title: 'Lucky Tree', tag: 'Slot', icon: '🌳', engine: 'slot', symbols: ['🌳','🪙','🍀','🍎','💎'] },
  { id: 6, title: 'Mystic Egg', tag: 'Slot', icon: '🥚', engine: 'slot', symbols: ['🥚','🐣','🪺','💎','👑'] },
  { id: 7, title: 'Fortune Tiger', tag: 'Slot', icon: '🐯', engine: 'slot', symbols: ['🐯','🎋','🪙','🧧','👑'] },
  { id: 8, title: 'Royal Lion', tag: 'Slot', icon: '🦁', engine: 'slot', symbols: ['🦁','👑','🛡️','🥩','💎'] },
  { id: 9, title: 'Phoenix Gold', tag: 'Slot', icon: '🔥', engine: 'slot', symbols: ['🔥','🦅','💎','👑','🪙'] },
  { id: 10, title: 'Lucky Panda', tag: 'Slot', icon: '🐼', engine: 'slot', symbols: ['🐼','🎋','🥢','🪙','💎'] },
  { id: 11, title: 'Divine Fortune', tag: 'Slot', icon: '✨', engine: 'slot', symbols: ['✨','🏛️','⚡','👑','🪙'] },
  { id: 12, title: 'Golden Dragon', tag: 'Slot', icon: '🐲', engine: 'slot', symbols: ['🐲','💎','🔥','👑','🪙'] },
  { id: 13, title: 'Fortune Temple', tag: 'Slot', icon: '🏛️', engine: 'slot', symbols: ['🏛️','🗿','🪙','🏺','👑'] },
  { id: 14, title: 'Monkey Treasure', tag: 'Slot', icon: '🐒', engine: 'slot', symbols: ['🐒','🍌','💎','🪙','👑'] },
  { id: 15, title: 'Magic Forest', tag: 'Slot', icon: '🌲', engine: 'slot', symbols: ['🌲','🍄','✨','🧚','💎'] },
  { id: 16, title: "Dragon's Treasure", tag: 'Slot', icon: '💎', engine: 'slot', symbols: ['💎','🐉','🪙','👑','⚔️'] },
  { id: 17, title: 'Royal Fortune', tag: 'Slot', icon: '👑', engine: 'slot', symbols: ['👑','💎','🪙','🍷','🛡️'] },
  { id: 18, title: 'Royal Dragon Tiger', tag: 'Dragon Tiger', icon: '🐉', engine: 'dragontiger' },
  { id: 19, title: 'Golden Dragon Tiger', tag: 'Dragon Tiger', icon: '🐲', engine: 'dragontiger' },
  { id: 20, title: 'Fortune Dragon Tiger', tag: 'Dragon Tiger', icon: '🍀', engine: 'dragontiger' },
  { id: 21, title: 'Mystic Dragon Tiger', tag: 'Dragon Tiger', icon: '🔮', engine: 'dragontiger' },
  { id: 22, title: 'Fortune Wheel', tag: 'Wheel', icon: '🎡', engine: 'wheel' },
  { id: 23, title: 'Royal Wheel', tag: 'Wheel', icon: '👑', engine: 'wheel' },
  { id: 24, title: 'Golden Wheel', tag: 'Wheel', icon: '🪙', engine: 'wheel' },
  { id: 25, title: 'Lucky Wheel', tag: 'Wheel', icon: '🍀', engine: 'wheel' },
  { id: 26, title: 'Wheel of Fortune', tag: 'Wheel', icon: '🎯', engine: 'wheel' }
];
